before_script:
  - bundle exec rake test_app
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  bundler: true

env:
  - DB=mysql
  - DB=postgres
language: ruby
rvm:
  - 2.4.0
  - 2.3.1
  - 2.2.7

sudo: false
